# Generated by Django 2.2.19 on 2023-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_images', verbose_name='Xidmət üçün şəkil')),
                ('title', models.TextField(help_text='Xidmət üçün başlıqi əlavə edin!', verbose_name='Xidmət üçün başlıq')),
                ('text', models.TextField(help_text='Xidmət üçün mətnini əlavə edin!', verbose_name='Xidmət 1 üçün mətn')),
            ],
            options={
                'verbose_name': 'Xidmət-in məlumati',
                'verbose_name_plural': 'Xidmət-in məlumati',
                'ordering': ('title',),
            },
        ),
    ]
