# Generated by Django 2.2.19 on 2023-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(help_text='Xidmət üçün mətnini əlavə edin!', verbose_name='Xidmət üçün mətn'),
        ),
    ]
