# Generated by Django 2.2.19 on 2023-03-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tag',
            field=models.TextField(help_text='Xidmət üçün qisa başlıqi əlavə edin!', max_length=16, verbose_name='Xidmət üçün qisa başlıq'),
        ),
    ]
