# Generated by Django 2.2.19 on 2023-03-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230307_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('title',), 'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər'},
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Alt Xidmət üçün başlıqi əlavə edin!', verbose_name='Alt Xidmət üçün başlıq')),
                ('text', models.TextField(help_text='Alt Xidmət üçün mətnini əlavə edin!', verbose_name='Alt Xidmət üçün mətn')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='services.Services')),
            ],
            options={
                'verbose_name': 'Alt Xidmət',
                'verbose_name_plural': 'Alt Xidmətlər',
                'ordering': ('title',),
            },
        ),
    ]
