# Generated by Django 2.2.19 on 2023-03-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20230307_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservice',
            options={'ordering': ('title',), 'verbose_name': 'Sub-xidmət', 'verbose_name_plural': 'Sub-xidmətlər'},
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(default=True, upload_to='subservices_images', verbose_name='Sub-service üçün şəkil'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(help_text='Ana xidməti seçin', on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='services.Services', verbose_name='Ana xidmət'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='text',
            field=models.TextField(help_text='Sub-service üçün mətnini əlavə edin!', verbose_name='Sub-service üçün mətn'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title',
            field=models.TextField(help_text='Sub-service üçün başlıqi əlavə edin!', verbose_name='Sub-service üçün başlıq'),
        ),
    ]
