# Generated by Django 2.2.19 on 2023-07-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20230727_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceDetailImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=True, upload_to='subservices_images_detail', verbose_name='Sub-service-Ətraflı üçün şəkil')),
            ],
            options={
                'verbose_name': 'şəkil',
                'verbose_name_plural': 'şəkiler',
            },
        ),
        migrations.RemoveField(
            model_name='subservicedetail',
            name='images',
        ),
        migrations.AddField(
            model_name='subservicedetail',
            name='images',
            field=models.ManyToManyField(blank=True, to='services.SubServiceDetailImageModel', verbose_name='Фотографии'),
        ),
    ]
