# Generated by Django 2.2.19 on 2023-07-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20230727_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservicedetailimagemodel',
            old_name='images',
            new_name='image',
        ),
    ]
