# Generated by Django 2.2.19 on 2023-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_service1_images', verbose_name='Ana səhifə Xidmət 1 üçün şəkil')),
                ('title', models.TextField(help_text='Ana səhifə 1 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifə Xidmət 1 üçün başlıq')),
                ('text', models.TextField(help_text='Ana səhifə 1 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifə Xidmət 1 üçün mətn')),
            ],
            options={
                'verbose_name': 'Ana səhifə Xidmət 1-in məlumati',
                'verbose_name_plural': 'Ana səhifə Xidmət 1-in məlumati',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HomeServiceThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_service3_images', verbose_name='Ana səhifə Xidmət 3 üçün şəkil')),
                ('title', models.TextField(help_text='Ana səhifə 3 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifə Xidmət 3 üçün başlıq')),
                ('text', models.TextField(help_text='Ana səhifə 3 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifə Xidmət 3 üçün mətn')),
            ],
            options={
                'verbose_name': 'Ana səhifə Xidmət 3-in məlumati',
                'verbose_name_plural': 'Ana səhifə Xidmət 3-in məlumati',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HomeServiceTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_service2_images', verbose_name='Ana səhifə Xidmət 2 üçün şəkil')),
                ('title', models.TextField(help_text='Ana səhifə 2 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifə Xidmət 2 üçün başlıq')),
                ('text', models.TextField(help_text='Ana səhifə 1 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifə 2 üçün mətn')),
            ],
            options={
                'verbose_name': 'Ana səhifə Xidmət 2-in məlumati',
                'verbose_name_plural': 'Ana səhifə Xidmət 2-in məlumati',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='HomeSlideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_slideshow_images', verbose_name='Ana səhifə Slaydşousu üçün şəkillər')),
            ],
            options={
                'verbose_name': 'Ana səhifə Slaydşou üçün şəkil',
                'verbose_name_plural': 'Ana səhifə Slaydşou üçün şəkillər',
                'ordering': ('id',),
            },
        ),
    ]
