# Generated by Django 2.2.19 on 2023-01-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeserviceone',
            options={'ordering': ('title',), 'verbose_name': 'Ana səhifənin Xidmət 1-in məlumati', 'verbose_name_plural': 'Ana səhifənin Xidmət 1-in məlumati'},
        ),
        migrations.AlterModelOptions(
            name='homeservicethird',
            options={'ordering': ('title',), 'verbose_name': 'Ana səhifənin Xidmət 3-ün məlumati', 'verbose_name_plural': 'Ana səhifənin Xidmət 3-ün məlumati'},
        ),
        migrations.AlterModelOptions(
            name='homeservicetwo',
            options={'ordering': ('title',), 'verbose_name': 'Ana səhifənin Xidmət 2-in məlumati', 'verbose_name_plural': 'Ana səhifənin Xidmət 2-in məlumati'},
        ),
        migrations.AlterModelOptions(
            name='homeslideshow',
            options={'ordering': ('id',), 'verbose_name': 'Ana səhifənin Slaydşou üçün şəkil', 'verbose_name_plural': 'Ana səhifənin Slaydşou üçün şəkillər'},
        ),
        migrations.AlterField(
            model_name='homeserviceone',
            name='image',
            field=models.ImageField(upload_to='home_service1_images', verbose_name='Ana səhifənin Xidmət 1 üçün şəkil'),
        ),
        migrations.AlterField(
            model_name='homeserviceone',
            name='text',
            field=models.TextField(help_text='Ana səhifənin 1 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifənin Xidmət 1 üçün mətn'),
        ),
        migrations.AlterField(
            model_name='homeserviceone',
            name='title',
            field=models.TextField(help_text='Ana səhifənin 1 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifənin Xidmət 1 üçün başlıq'),
        ),
        migrations.AlterField(
            model_name='homeservicethird',
            name='image',
            field=models.ImageField(upload_to='home_service3_images', verbose_name='Ana səhifənin Xidmət 3 üçün şəkil'),
        ),
        migrations.AlterField(
            model_name='homeservicethird',
            name='text',
            field=models.TextField(help_text='Ana səhifənin 3 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifənin Xidmət 3 üçün mətn'),
        ),
        migrations.AlterField(
            model_name='homeservicethird',
            name='title',
            field=models.TextField(help_text='Ana səhifənin 3 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifənin Xidmət 3 üçün başlıq'),
        ),
        migrations.AlterField(
            model_name='homeservicetwo',
            name='image',
            field=models.ImageField(upload_to='home_service2_images', verbose_name='Ana səhifənin Xidmət 2 üçün şəkil'),
        ),
        migrations.AlterField(
            model_name='homeservicetwo',
            name='text',
            field=models.TextField(help_text='Ana səhifənin 1 Xidmət üçün mətnini əlavə edin!', verbose_name='Ana səhifənin 2 üçün mətn'),
        ),
        migrations.AlterField(
            model_name='homeservicetwo',
            name='title',
            field=models.TextField(help_text='Ana səhifənin 2 Xidmət üçün başlıqi əlavə edin!', verbose_name='Ana səhifənin Xidmət 2 üçün başlıq'),
        ),
        migrations.AlterField(
            model_name='homeslideshow',
            name='image',
            field=models.ImageField(upload_to='home_slideshow_images', verbose_name='Ana səhifənin Slaydşousu üçün şəkillər'),
        ),
    ]
