# Generated by Django 2.2.19 on 2023-03-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230125_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=50)),
                ('field2', models.IntegerField()),
                ('field3', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
