# Generated by Django 2.2.19 on 2023-03-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
