# Generated by Django 2.2.19 on 2023-01-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstupfront', models.ImageField(upload_to='firstUp/front', verbose_name='Yuxarıdakı 1 ci şekilin üz terefi')),
                ('firstupback', models.ImageField(upload_to='firstUp/back', verbose_name='Yuxarıdakı 1 ci şekilin alt terefi')),
                ('secondupfront', models.ImageField(upload_to='secondUp/front', verbose_name='Yuxarıdakı 2 ci şekilin üz terefi')),
                ('secondupback', models.ImageField(upload_to='secondUp/back', verbose_name='Yuxarıdakı 2 ci şekilin alt terefi')),
                ('firstdownfront', models.ImageField(upload_to='firstDown/front', verbose_name='Aşağıdaki 1 ci şekilin üz terefi')),
                ('firstdownback', models.ImageField(upload_to='firstDown/back', verbose_name='Aşağıdaki 1 ci şekilin alt terefi')),
                ('seconddownfront', models.ImageField(upload_to='secondDown/front', verbose_name='Aşağıdaki 2 ci şekilin üz terefi')),
                ('seconddownback', models.ImageField(upload_to='secondDown/back', verbose_name='Aşağıdaki 2 ci şekilin alt terefi')),
            ],
            options={
                'verbose_name': 'Haqqımızda səhifəsinin şəkilləri',
                'verbose_name_plural': 'Haqqımızda səhifəsinin şəkilləri',
            },
        ),
    ]
